version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@istanbuljs/nyc-config-typescript"
    versions:
    - 1.0.1
  - dependency-name: helmet
    versions:
    - 4.5.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/uuid"
    versions:
    - 8.3.0
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.1
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.3.0
    - 7.3.4
  - dependency-name: cypress
    versions:
    - 3.8.3
    - 4.12.1
    - 7.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: tree-kill
    versions:
    - 1.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: polished
    versions:
    - 4.1.2
  - dependency-name: husky
    versions:
    - 6.0.0
  - dependency-name: "@types/faker"
    versions:
    - 5.5.3
  - dependency-name: graphql
    versions:
    - 15.5.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.4
  - dependency-name: "@cypress/code-coverage"
    versions:
    - 3.9.5
  - dependency-name: ts-loader
    versions:
    - 9.1.1
  - dependency-name: raw-loader
    versions:
    - 4.0.2
  - dependency-name: postcss
    versions:
    - 8.2.13
  - dependency-name: isomorphic-fetch
    versions:
    - 3.0.0
  - dependency-name: next
    versions:
    - 10.1.3
    - 9.3.2
  - dependency-name: "@types/http-proxy-middleware"
    versions:
    - 1.0.0
  - dependency-name: node-sass
    versions:
    - 4.13.1
    - 5.0.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.13.13
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 2.34.0
  - dependency-name: "@auth0/auth0-spa-js"
    versions:
    - 1.13.6
    - 1.14.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
    - 7.13.0
  - dependency-name: apollo-server-core
    versions:
    - 2.19.2
    - 2.21.0
    - 2.21.2
    - 2.23.0
  - dependency-name: acorn
    versions:
    - 6.4.2
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: apollo-server-micro
    versions:
    - 2.14.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: dot-prop
    versions:
    - 5.3.0
  - dependency-name: "@types/mongodb"
    versions:
    - 3.6.10
    - 3.6.11
    - 3.6.12
    - 3.6.3
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
  - dependency-name: "@types/express"
    versions:
    - 4.17.11
  registries:
  - npm-registry-npm-fontawesome-com
